// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPiAllRlqGuYMrfGQx9UqsSgEWLefFt9c',
    appId: '1:138130649234:web:5e21b859c4c4fc0fb4764b',
    messagingSenderId: '138130649234',
    projectId: 'roomie-65558',
    authDomain: 'roomie-65558.firebaseapp.com',
    storageBucket: 'roomie-65558.appspot.com',
    measurementId: 'G-7MQNTBE6B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGF3wLBbkqFaIajBUhk3XeyFV3vQG2Zsc',
    appId: '1:138130649234:android:25519e469f64948bb4764b',
    messagingSenderId: '138130649234',
    projectId: 'roomie-65558',
    storageBucket: 'roomie-65558.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnfU9XVSnh3pdwPrCZgXOrHVbOmrXY_-E',
    appId: '1:138130649234:ios:15a643ea6b2944c7b4764b',
    messagingSenderId: '138130649234',
    projectId: 'roomie-65558',
    storageBucket: 'roomie-65558.appspot.com',
    iosBundleId: 'lwamzeche.com.roomieProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnfU9XVSnh3pdwPrCZgXOrHVbOmrXY_-E',
    appId: '1:138130649234:ios:f2f28a29f2b96c2eb4764b',
    messagingSenderId: '138130649234',
    projectId: 'roomie-65558',
    storageBucket: 'roomie-65558.appspot.com',
    iosBundleId: 'lwamzeche.com.roomieProject.RunnerTests',
  );
}
